# Generated by Django 3.2.16 on 2022-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('stock_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stock_cap', models.CharField(max_length=100)),
                ('themas', models.CharField(max_length=300)),
            ],
        ),
    ]
